### ISSUE TITLE
Compatibility with other tools

### ISSUE THREAD

**Issue by mwang87** [mobiusklein/psims#10]
This is a great tool! I love it. One suggestion for other users, is the output is not fully compatible with tools taking in mzML. To help with this, simply doing a round trip mzML -> mzML conversion in proteowizard's msconvert totally fixes things.

**Comment by mobiusklein** [comment]
Hello,

Could you please point me to where the produced file is incompatible, and with which tool? At least at the time of publication, the files produced were schematically and semantically valid.

**Comment by bkalafut1** [comment]
We had this problem with Skyline and traced it back to ProteoWizard's import library, through a code path probably not used by MSConvert.  It also shows up in SeeMS.  One of our engineers found that msConvert to mxXML and back to mxML fixes it.  After a deep dive in ProteoWizard I think I found root cause.

The default ID is of the format SPECTRUM_0 here, but ProteoWizard expects at least one = character somewhere in the id string.

The problem isn't ProteoWizard's, although they are (uniquely) particular about an obscure part of the mzML standard.  Per the mzML standard the ID is to match the pattern \S+=\S+( \S+=\S+)* 

That single space between the ( and the third \S appears to be deliberate, too.
So the IDs are not unlike "FOO=2 BAR=EBOLASAMPLE BAZ=65535"

When constructing an ID from the index instead of an _ an = should be used in this context.  Passing an ID that matches this format to write_spectrum, e.g. id=f"index={sid}" where sid is my internal integer, is a workaround.  In your examples your IDs always match the standards so you produce up-to-standard mzML but the default ID generator does not.  

I see in the code that the piece that makes an ID from an int is not specific to the Spectrum.  Adding some logic to the spectrum constructor is a partial fix.  I'll fork and submit a PR with this lightweight and partial fix.  It's possible to check that the ID matches the pattern and error out, too, but whether the overhead of a regex match is desirable here is a question I don't have much feel for.

**Comment by bkalafut1** [comment]
Scratch that note about the pull request.  I'm not seeing how to keep spectrum_reference consistent if applying a very quick fix, and will stick with my workaround for now.

**Comment by mobiusklein** [comment]
Thank you for providing additional details. I think I see a way to fix this. Managing nativeID formats explicitly is a clear functionality gap and violates the expectation that the ID mapping just "works".

Switching to either the `index={number}` or similar when the ID is given as an integer or finding an appropriate ID when the inferred or specified nativeID format is given should be doable (to a point)

**Comment by mobiusklein** [comment]
@bkalafut1 @mwang87 could you please try out #17 and let me know if it solves your issue with using integer spectrum IDs?

**Comment by mwang87** [comment]
Great, will give it a try over the next few days. I'll test compatibilty with our readers in GNPS and MassQL

**Comment by bkalafut1** [comment]
I should be able to try this by the end of the week.
